# Generated by Django 5.0.6 on 2024-06-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(blank=True, choices=[('used', 'Used'), ('new', 'New')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('mobiles', 'Mobiles'), ('pets', 'Pets'), ('fashion', 'Fashion'), ('book', 'Books'), ('furniture', 'Furniture'), ('electronics', 'Electronics & Appliances'), ('properties', 'Properties'), ('sports', 'Sports'), ('commercial_vehicle', 'Commercial Vehicle Spares')], max_length=50),
        ),
    ]
