# Generated by Django 5.0.6 on 2024-07-02 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_listing_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='seller',
        ),
    ]
